# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba1eef817a3202190ccc62051d94cb26d9cecc57ac51d6206da675fad4b5ee040bcd2b152d425ee8f9fffa4cc98c50903cb7a9bf9d2244148531360482b641ab

test:
  secret_key_base: 48b813205d7e35d5cebc3791860cf7be138b3f2822e3eba16d0c940bac58b033129a92ba72e8e3041c4454891d899d2e021828f723f48bed1de32ef1c674bbc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
